core/urls.py
# coding=utf-8
__author__ = 'Artur Bacmaga'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'registration/logout.html'}, name="logout"),

                       url(r'^manage_users/$', 'core.views.manage_users', name="manage-users"),
                       url(r'^manage_users/adduser/$', 'core.views.adduser', name="add-user"),
                       url(r'^manage_users/edituser/(?P<user_id>\d+)/$', 'core.views.edit_user', name="edit-user"),
                       url(r'^manage_users/deleteuser/$', 'core.views.delete_user',
                           name="delete-user"),

                       url(r'^manage_users/edituser/(?P<user_id>\d+)/password/$', 'core.views.admin_change_password',
                           name="admin-change-password"),

                       url(r'^user_data/$', 'core.views.user_data', name="user-data"),
                       url(r'^user_password/$', 'core.views.user_password', name="user-password"),
)

page/models.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@gmail.com>
# Author Bartłomiej Wójcicki <bartlomiej.wojcicki@agitive.com>
# Author Witold Sosnowski <albi@jabster.pl>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.conf import settings
import json


# content types
MENU = 'menu'
TEXT = 'text'
LIST = 'list'
STEPS = 'stps'
CONTACT = 'cont'
CATEGORY = 'cate'

# special types
HEADLINES = 'head'
VIDEOS = 'vids'
FACEBOOK = 'face'

# file manager
FILES = 'file'

# faq
FAQ = 'faqs'

# visa application status
STATUS = 'stat'
PASSPORT = 'pasp'


# zoom
LOW = 11
NORMAL = 13
HIGH = 15

class Page(models.Model):
	TYPES_WITH_CONTENT = (TEXT, LIST, STEPS, CONTACT, CATEGORY)
	PARENT_TYPES = (MENU, LIST, STEPS, CATEGORY)
	SPECIAL_TYPES = (HEADLINES, VIDEOS, FILES, FAQ)
	PAGE_TYPES = (
		(MENU, 'Menu'),
		(TEXT, 'Text'),
		(LIST, 'List'),
		(STEPS, 'Steps'),
		(CATEGORY, 'Table structure'),
		(CONTACT, 'Contact info'),
		(STATUS, 'Visa application status'),
		(PASSPORT, 'Passport tracker'),
		(FAQ, 'Frequently Asked Questions'),
		(VIDEOS, 'Videos'),
		(FILES, 'File Manager'),
		(HEADLINES, 'Headlines'),
		(FACEBOOK, 'Facebook'),
	)
	STATUS_CHOICES = (
		(LOW, 'Low'),
		(NORMAL, 'Normal'),
		(HIGH, 'High'),
	)

	parent_page = models.ForeignKey('self', blank=True, null=True, related_name='child_page',
									limit_choices_to={'page_type__in': PARENT_TYPES})

	permission_parent = models.ForeignKey('self', blank=True, null=True, related_name='permission_child_page',
											editable=False)
	is_permission_parent = models.BooleanField(default=False)

	page_type = models.CharField(max_length=4, choices=PAGE_TYPES, default=TEXT)

	title_pl = models.CharField('Title (PL)', max_length=settings.TITLE_LENGTH)
	title_en = models.CharField('Title (EN)', max_length=settings.TITLE_LENGTH)

	version = models.IntegerField(default=0)
	created = models.DateTimeField(default=timezone.now)
	modified = models.DateTimeField(default=timezone.now)

	active = models.BooleanField(default=True, editable=False)

	#dane dotyczace struktury drzewa
	level = models.IntegerField(default=0, editable=False)  #parent.level+1
	place = models.IntegerField(default=0, editable=False)  #kolejność

	content_pl = models.TextField(verbose_name='Content (PL)', blank=True)
	content_en = models.TextField(verbose_name='Content (EN)', blank=True)

	additional_pl = models.TextField(verbose_name='Additional (PL)', blank=True)
	additional_en = models.TextField(verbose_name='Additional (EN)', blank=True)

	latitude = models.FloatField("Latitude", blank=True, null=True, default=52.229902,
	                             help_text="degrees, floating point, South is negative")
	longitude = models.FloatField("Longitude", blank=True, null=True, default=21.012669,
	                              help_text="degrees, floating point, West is negative")

	zoom = models.IntegerField(blank=True, null=True, default=NORMAL, choices=STATUS_CHOICES)

	editors = models.ManyToManyField(User, related_name='edited_pages')

	def to_dict(self):
		def child_to_dict(child):
			return {
				'id': child[0],
				'index': child[1],
				'title_pl': child[2],
				'title_en': child[3]
			}

		def fix_content(content):
			if content == '':
				return '<content></content>'
			fixed_content = content.replace('&nbsp;', ' ')
			fixed_content = fixed_content.replace('<p><a', '<a').replace('</a></p>', '</a>')
			fixed_content = fixed_content.replace('<li><p>', '<li>').replace('</p></li>', '</li>')
			fixed_content = fixed_content.replace('\t', '').replace('\r', '').replace('\n', '')
			fixed_content = fixed_content.replace('<br />', '\n').replace('<br/>', '\n')
			return fixed_content

		def fix_faq(content):
			try:
				faq_list = json.loads(content)
			except:
				return '[]'

			for question in faq_list:
				question['answer'] = fix_content(question['answer'])

			return json.dumps(faq_list)

		parent_id = 0
		if self.parent_page_id is not None:
			parent_id = self.parent_page_id

		data = {
			'id': self.id,
			'parent_id': parent_id,
			'title_pl': self.title_pl,
			'title_en': self.title_en,
			'version': self.version,
			'type': self.type(),
			'index': self.place,
			#'created': self.created.date().isoformat(),
			#'modified': self.modified.date().isoformat(),
			#'level': self.level,
			#'place': self.place
		}

		type = self.page_type
		if type in self.TYPES_WITH_CONTENT:
			data['content_pl'] = fix_content(self.content_pl)
			data['content_en'] = fix_content(self.content_en)
			if self.additional_en and self.additional_pl:
				data['additional_pl'] = fix_content(self.additional_pl)
				data['additional_en'] = fix_content(self.additional_en)

		if type == CONTACT:
			if self.latitude:
				data['latitude'] = self.latitude
			if self.longitude:
				data['longitude'] = self.longitude
			if self.zoom:
				data['zoom'] = self.zoom

		if type == FAQ:
			data['faq_en'] = fix_faq(self.content_en)
			data['faq_pl'] = fix_faq(self.content_pl)

		if type == CATEGORY:
			# type CATEGORY is used only server side
			data['type'] = TEXT

		children = self.child_page.filter(active=True).values_list('id', 'place', 'title_pl', 'title_en')
		data['children'] = map(child_to_dict, children)
		return data

	def to_json(self):
		data = self.to_dict()
		return json.dumps(data)

	def save(self, *args, **kwargs):
		self.version += 1
		self.modified = timezone.now()
		previous_level = self.level
		previous_permission_parent = self.permission_parent

		if self.parent_page is not None:
			self.level = self.parent_page.level + 1
			if self.is_permission_parent:
				self.permission_parent = None
			else:
				if self.parent_page.is_permission_parent:
					self.permission_parent = self.parent_page
				else:
					self.permission_parent = self.parent_page.permission_parent
		else:
			self.permission_parent = None
			self.is_permission_parent = True
			self.level = 0

		super(Page, self).save(*args, **kwargs)

		if self.level != previous_level or self.permission_parent != previous_permission_parent:
			for child in self.child_page.filter(active=True):
				child.save()

	def __unicode__(self):
		return unicode(self.title_en)

	def get_children_set(self):
		return set(Page.objects.filter(parent_page=self, active=True))

	def type(self):
		return self.page_type

	def type_name(self):
		return dict(Page.PAGE_TYPES).get(self.page_type)

	def user_can_add_children(self, user):
		if self.user_can_edit(user):
			return True
		if self.is_permission_parent:
			perm_parent = self
			while perm_parent is not None and perm_parent.editors.filter(pk=user.pk).count() == 0:
				perm_parent = perm_parent.parent_page
				if perm_parent is None:
					break
				# goto next permission parent
				if not perm_parent.is_permission_parent:
					perm_parent = perm_parent.permission_parent

			return perm_parent is not None
		return False

	def user_can_edit(self, user):
		if user.has_perm('page.change_page'):
			return True
		if self.is_permission_parent:
			return False
		return self.permission_parent.editors.filter(pk=user.pk).count() > 0

	def user_can_remove(self, user):
		if self.is_permission_parent:
			return False
		return self.user_can_edit(user)

	def are_children_valid(self, children):
		if children is None:
			return True
		
		children = list(children)
		child_pages = Page.objects.filter(pk__in=children)
		valid = not any(self.is_descendant(child) for child in child_pages)
		return valid

	def update_children(self, children):
		children = list(children)
		if self.child_page.filter(active=True, is_permission_parent=True).count() > 0:
			children_check = self.child_page.filter(active=True).values_list('id', flat=True)
			if set(children_check) != set(children):
				raise Exception('Cannot delete a permission parent!')
		for child in self.child_page.filter(active=True):
			try:
				child.place = children.index(child.id)
				children[child.place] = 0
				child.save()
			except Exception, e:
				child.deactivate()

		for id in children:
			if id > 0:
				page = Page.objects.get(id=id)
				page.move_to_parent(self)
				page.place = children.index(id)
				page.save()

	def move_to_parent(self, parent):
		old_parent = self.parent_page

		if old_parent == parent:
			return

		self.parent_page = parent

		i = 0
		for child in old_parent.child_page.filter(active=True).order_by('place'):
			child.place = i
			child.save()
			i += 1

		# self.save() called later

	def deactivate(self):
		self.active = False
		self.save()
		map(lambda x: x.deactivate(), self.child_page.filter(active=True))

	def convert_to_data_args(self):
		def data_args(content):
			fixed_content = content.replace('page=', 'data-page=')
			fixed_content = fixed_content.replace('url=', 'data-url=')
			fixed_content = fixed_content.replace('address=', 'data-address=')
			fixed_content = fixed_content.replace('number=', 'data-number=')
			return fixed_content

		changed = False
		if self.content_en:
			self.content_en = data_args(self.content_en)
			changed = True
		if self.content_pl:
			self.content_pl = data_args(self.content_pl)
			changed = True
		if self.additional_en:
			self.additional_en = data_args(self.additional_en)
			changed = True
		if self.additional_pl:
			self.additional_pl = data_args(self.additional_pl)
			changed = True
		if changed:
			self.save()

	def is_descendant(self, page):
		current_page = self

		while current_page.parent_page is not None and current_page.parent_page != page:
			current_page = current_page.parent_page

		return current_page.parent_page is not None

	def convert_to_categories(self):
		def has_categories(content):
			index = content.find("\"categories\"")
			return index != -1

		if self.page_type == CATEGORY:
			return

		convert = False
		if self.content_en and has_categories(self.content_en):
			convert = True

templates/page/add_child_modal.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}add-child-modal{% endblock %}


{% block dialog_title %}Add child{% endblock %}

{% block dialog_body %}
<div class="text-center">
    <a href="{% url "add-child-page" page.id %}" id="create-child-url" class="btn btn-lg">CREATE NEW</a>
    <span class="select-existing">or select existing</span>
    {% include 'page/content_tree.html' with tree=full_tree widget_id='add_child_modal' show_select=True %}
    <script type="text/javascript">
    $(function(){
        $('#add-child-modal .content-tree').on('click', '.btn', function(){
            var template = '<li id="child_{0}" data-id="{0}">{1}</li>';
            var txt = template.format($(this).parent().data('id'), $(this).parent().directText());
            $('#add-child-modal').modal('toggle');
            $('#items-list').append(txt);
            return false;
        });
    });
    </script>
</div>
{% endblock %}

templates/page/add_page_modal.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}add-page-modal{% endblock %}

{% block dialog_class %}
	in modal-visible
{% endblock %}

{% block dialog_title %}Add action page{% endblock %}

{% block dialog_action %}{% url 'add-page-modal' page_id %}{% endblock %}

{% block dialog_body %}
    {% include 'form.html' %}
{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Add page" %}
</button>
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
$('#add-page-modal textarea').each(function(){
    CKEDITOR.replace($(this)[0], {
	    extraPlugins: 'btn',
	    toolbar: [['Btn', 'h1', 'h2', 'Bold', 'NumberedList', 'BulletedList',  'Format' ]],
	    allowedContent: 'p h1 h2[id]; ol ul li[id]; strong[id]; a(btn)[*];',
	    on: {
	        afterPaste: afterPasteFix,
	        instanceReady: setupEvents,
	        key: blockTab
	    },
	    contentsCss: [
	        CKEDITOR.basePath + 'contents.css',
	        '/static/css/contents_.css',
	        '/static/css/contents_small.css',
	    ],
	    height: 150
	});
});

$('#add-page-modal form').ajaxForm({
    target:'#add-page-modal',
    beforeSerialize: function()
    {
        for(var instanceName in CKEDITOR.instances)
        {
        	$('#add-page-modal').find('#'+instanceName).val(CKEDITOR.instances[instanceName].getData());
        	console.log($('#add-page-modal').find('#'+instanceName))
            console.log($('#add-page-modal').find('#'+instanceName).val())
        }
    },
    success: function(data)
    {
        if(isNumber(data))
        {
            __global_element.setAttribute('data-page', data);
            $('#add-page-modal').modal('hide');
            $('#add-page-modal').data('bs.modal', null);
            $('#add-page-modal').html('');
        }
    }
});
</script>
{% endblock %}

templates/page/content_tree.html
{% load static %}

<h4 class="content-tree-header text-center">
	CONTENT TREE <img src="{% static 'img/tree_opened.png' %}">
</h4>
<ul class="content-tree" id="{{ widget_id }}">
{% for item in tree %}
<li>
	<span class="trow">
		<span class="{% if item.items_count > 0 %}open{% else %}empty{% endif %} arrow link" data-id="{{ item.id }}">
			{{ item.title_en }}
			{% if show_edit %}
				<a href="/cms/edit_page/{{ item.id }}/" class="btn btn-default btn-sm pull-right">EDIT</a>
			{% elif show_select %}
				<a href="#" class="btn btn-default btn-sm pull-right">SELECT</a>
			{% endif %}
		</span>
	</span>
	<ul>
	</ul>
</li>
{% endfor %}
</ul>

<script type="text/javascript">
if (!String.prototype.format) {
  String.prototype.format = function() {

    var args = arguments;
    var sprintfRegex = /\{(\d+)\}/g;

    var sprintf = function (match, number) {
      return number in args ? args[number] : match;
    };

    return this.replace(sprintfRegex, sprintf);
  };
}

$(function(){
	$('#{{ widget_id }}.content-tree').on('click', 'a', function(e){
		e.stopPropagation();
	});
	$('#{{ widget_id }}.content-tree').off('click', 'span.arrow').on('click', 'span.arrow', function(e){
		var $self = $(this);
		var $content = $self.closest('li').children('ul');
		if($self.hasClass('open'))
		{
			$content.slideUp();
		}			
		if($self.data('loaded'))
		{
			$content.slideDown();
			$(this).removeClass('open');
			$(this).addClass('opened');
			return false;
		}

		var page_id = $self.data('id');
		$.get('{% url "page-content-tree" %}'+page_id, function(data){
			var $content = $self.closest('li').children('ul');
			var template = 
				'<li>' +
				'	<span class="trow">' +
				'		<span class="open arrow link" data-id="{0}">' +
				'			{1} ' +
			{% if show_edit %}
				' 			<a href="/cms/edit_page/{0}/" class="btn btn-default btn-sm pull-right">EDIT</a>' +
			{% elif show_select %}
				' 			<a href="#" class="btn btn-default btn-sm pull-right">SELECT</a>' +
			{% endif %}
				'		</span>' +
				'	</span>' +
				'	<ul></ul>' +
				'</li>';

			if(data[0].items.length == 0)
			{
				$self.addClass('empty');
				$self.removeClass('open');
				$self.removeClass('opened');
			}
			else
			{
				$.each(data[0].items, function( index, value ) {
					var html = template.format(value.id, value.title_en);
					var $html = $(html);
					if(value.items_count == 0)
						$html.find('.trow span').removeClass('open').addClass('empty');
					$content.append($html);
				});
				$content.slideDown();
			}
			$self.data('loaded', true);
			$self.data('content', data);
			if($self.hasClass('arrow'))
			{
				$self.removeClass('open');
				$self.addClass('opened');
			}
			e.preventDefault();
		});
		e.preventDefault();
	});

	$('#{{ widget_id }}.content-tree').off('click', 'span.opened').on('click', 'span.opened', function(e){
		var $content = $(this).closest('li').children('ul');
		$content.slideUp();
		$(this).removeClass('opened');
		$(this).addClass('open');
		e.preventDefault();
	});
});
</script>

templates/page/edit_contact.html
{% extends "page/edit_page.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}

templates/page/edit_faq.html
{% extends "page/edit_page_partial.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block children %}
<div class="form-group">    
    <label class="lang-en">Frequently asked questions (EN)</label>
    <div id="faq-en" class="faq">
    <button class="add-question btn btn-lg btn-block">
        <img src="{% static "img/add.png" %}"> Add question
    </button>
    </div>
</div>
<div class="form-group">    
    <label class="lang-pl">Frequently asked questions (PL)</label>
    <div id="faq-pl" class="faq">
    <button class="add-question btn btn-lg btn-block">
        <img src="{% static "img/add.png" %}"> Add question
    </button>
    </div>
</div>
<script type="text/javascript">
$(function(){
    showFAQs('en');
    showFAQs('pl');
    $('#save-button').click(function() {
        for(var instanceName in CKEDITOR.instances)
            CKEDITOR.instances[instanceName].updateElement();

        saveFAQs('en');
        saveFAQs('pl');
    });
    $('.add-question').click(function() {
        question = $('<div class="question">' +
                '<textarea placeholder="Question" class="question"></textarea>' +
                '<button class="remove-question"></button>' +
                '<textarea placeholder="Answer" class="answer"></textarea>' +
                '</div>');
        question.insertBefore($(this));
        $txtarea = question.find('.answer');
        installEditor($txtarea[0]);
        return false;
    });

});

function installEditor(element)
{
    CKEDITOR.replace(element, {
        extraPlugins: 'phone,hours,address,mail,btn,ajax,xml',
        toolbar: [['Phone', 'Hours', 'Address', 'Contact', 'Mail', 'Btn', 'Bold', 'NumberedList', 'BulletedList']],
        allowedContent: 'div(*)[*]; p[id]; ol ul li[id]; strong[id]; a(btn)[*];',
        contentsCss: [
            CKEDITOR.basePath + 'contents.css',
            '/static/css/contents_.css'
        ],
        on: {
            afterPaste: afterPasteFix,
            instanceReady: setupEvents,
            key: blockTab
        }
    });
}

function showFAQs(lang) 
{
    json = $('#id_content_' + lang).val();
    console.log(json);
    if (!json) {
        json = '[]';
    }
    try
    {
        obj = JSON.parse(json);
    }
    catch (e)
    {
        obj = new Array();
    }

    len = obj.length;
    for(i = 0; i< len; ++i) {
        question = $('<div class="question"></div>');
        question.append('<textarea placeholder="Question" class="question">' + obj[i].question + '</textarea>');
        question.append('<button class="remove-question"></button>');
        question.append('<textarea placeholder="Answer" class="answer">' + obj[i].answer + '</textarea>');
        question.insertBefore($('#faq-' + lang + ' > .add-question'));

        $txtarea = question.find('.answer');
        installEditor($txtarea[0]);
    }

};
function saveFAQs(lang) {    
    faqs = $('#faq-' + lang + ' > .question').map(function(i, e) {
        obj = new Object();
        obj.question = e.children[0].value;
        obj.answer = e.children[2].value;
        return obj;
    }).get();
    $('#id_content_' + lang).val(JSON.stringify(faqs));
};
</script>
{% endblock %}

templates/page/edit_list.html
{% extends "page/edit_page_partial.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block children %}
<div class="form-group">
    <label>Children:</label>
    <ul class="sortable stick-bottom" id="items-list">
    {% for child in children %}
        <li id="child_{{ child.id }}" data-id="{{ child.id }}">{{ child.title_en }}</li>
    {% endfor %}
    </ul>
    
    {% include 'page/add_child_modal.html' with no_form=True %}

    <div class="btn-group" id="children-menu">
        <a data-toggle="modal" data-target="#add-child-modal" class="btn btn-lg">
            <img src="{% static 'img/add.png' %}">
            {% trans "NEW" %}
        </a>

        <ul id="remove-item" title="Drag item here to remove it" class="hover-tooltip">
            <img src="{% static 'img/remove.png' %}">
            {% trans "REMOVE" %}
        </ul>
    </div>
    <script type="text/javascript">
    installSortables();
    </script>
</div>
{% endblock %}

templates/page/edit_page.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}
{% load addclass %}

{% block title %}Edit Page{% endblock %}

{% block wysiwyg_scripts %}    

    <script type="text/javascript" src="{% static "js/jquery.form.min.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor.js" %}"></script>
    <script type="text/javascript" src="{% static "js/page.js" %}"></script>
    {% if page %}
    <script type="text/javascript">
    page_id = {{ page.id }}
    $(function(){
        $('#form-content').on('change', '#id_page_type', function(){
            $.get("{% url 'edit-page-partial' page.id %}", {page_type:$(this).val()}, function(result){
                $('#page-edit-form').replaceWith(result);
            });
        });
    });
    </script>
    {% endif %}
{% endblock %}

{% block header_styles %}
<link rel="stylesheet" href="/static/css/page.css">
<link rel="stylesheet" href="/static/css/content-tree.css">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4" id="left-panel">
        <div class="row">
            <div class="col-md-6">
            {% if page.parent_page_id %}
                <a href="{% url 'edit-page' page.parent_page_id %}" id="parent-link" class=" btn btn-primary btn-block">
                <img src="/static/img/arrow_back.png"> {% trans "TO PARENT" %}
            {% else %}
                <a href="{% url 'page-home' %}" id="parent-link" class=" btn btn-primary btn-block">
                <img src="/static/img/arrow_back.png"> {% trans "BACK" %}
            {% endif %}
            </a>
            </div>
        </div>

        {% include "page/content_tree.html" with show_edit=True widget_id='edit_page' %}
    </div>

    <div class="col-md-8" id="form-content">
    <h1 class="text-center">Edit Page</h1>
    <div class="text-right clearfix" id="lang-switcher">
        Language: 
        <a href="" id="lang-switch-en" data-lang="en" class="lang-switch active">EN</a><a href="" id="lang-switch-pl" data-lang="pl" class="lang-switch">PL</a>
    </div>
    
    {% include page_template %}
    </div>

    <div class="modal fade" id="add-page-modal" role="dialog" aria-hidden="true">
    </div>

</div>
{% endblock %}

templates/page/edit_page_partial.html
{% load i18n %}
{% load url from future %}
{% load staticfiles %}
{% load addclass %}

<script type="text/javascript">
function afterPasteFix(e)
{
    ed = e.editor;
    ed.widgets.checkWidgets();
    selected = ed.getSelection().getStartElement();
    selected.setAttribute('id', 'last-selected');
    data = ed.getData();
    $.post('/cms/clean_text/', { data: data }, function(cleaned_data) {
        ed.setData(cleaned_data);
    });
}

function setupEvents(e)
{
    e.editor.on('toHtml', function(evt) {
        ed = evt.editor;
        selected = ed.document.getById('last-selected');
        if (selected != null) {
            selected.removeAttribute('id');
            range = ed.createRange();
            range.selectNodeContents(selected);
            range.collapse();
            ed.getSelection().selectRanges([range]);
            selected.scrollIntoView();
        }
    }, null, null, 20 );
}

function blockTab(e)
{
    var key = e.data.keyCode;
    if (key==9) {
        return false;
    }
}
</script>

<form action="" method="post" role="form" id="page-edit-form">
    {% csrf_token %}
    {% if form.errors %}
        <p class="alert alert-danger"> {% trans "Please fix form errors."%}
        </p>
    {% endif %}
    {% if saved %}
        <p class="alert alert-success" id="page-saved-msg">
            {% trans "Page saved." %}
        </p>
    {% endif %}
    {% if form.non_field_errors or children_error %}
        <p class="alert alert-danger">
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    {{ error|escape }}
                {% endfor %}
            {% endif %}
            {% if children_error %}
                {{ children_error|escape }}
            {% endif %}
        </p>
    {% endif %}
    {% for field in form.hidden_fields %}
        {{ field }}        
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="form-group">
        {{ field.label_tag }}
        
        {% if field.errors %}
        <p class="alert alert-danger">
            {% for error in field.errors %}
                {{ error|escape }}
            {% endfor %}
        </p>
        {% endif %}
        {{ field }}
        </div>
    {% endfor %}

    {% block children %}
    {% endblock %}

    <button type="submit" class="btn btn-lg btn-block" id="save-button">
        <img src="/static/img/save.png"> SAVE CHANGES
    </button>

</form>
<script type="text/javascript">
    
    $(function(){
        $('.lang-pl').parent().hide();
    });

    $('.lang-switch').click(function(){
        $('.lang-switch').removeClass('active');
        $(this).addClass('active');
        var lang = $(this).data('lang');
        var prev_lang = (lang == 'en' ? 'pl' : 'en');
        $('.lang-'+lang).parent().show();
        $('.lang-'+prev_lang).parent().hide();
        return false;
    });

    $('#page-edit-form').click(function() {
       $('#page-saved-msg').hide();
    });


    delete CKEDITOR.dtd.p.img;
    CKEDITOR.dtd.$block.img = 1;

    $('#page-edit-form textarea[name^="content"]').map(function(i, e) {
        CKEDITOR.replace(e, {
        {% if page.page_type == 'cate' %}
            extraPlugins: 'phone,hours,address,mail,btn,info,categories,ajax,xml',
            toolbar: [
                ['Phone', 'Hours', 'Address', 'Contact', 'Mail', 'Btn', 'Info', 'Categories'],
                '/',
                ['h1', 'h2', 'Bold', 'NumberedList', 'BulletedList', 'Image', 'Format']
            ],
        {% endif %}
            on: {
                afterPaste: afterPasteFix,
                instanceReady: setupEvents,
                key: blockTab
            }
        });
    });
    $('#page-edit-form textarea[name^="additional"]').map(function(i, e) {
        CKEDITOR.replace(e, {
            extraPlugins: 'btn,xml,ajax',
            toolbar: [['Btn', 'h1', 'h2', 'Bold', 'NumberedList', 'BulletedList',  'Format' ]],
            allowedContent: 'p h1 h2[id]; ol ul li[id]; strong[id]; a(btn)[*];',
            on: {
                afterPaste: afterPasteFix,
                instanceReady: setupEvents,
                key: blockTab
            },
            contentsCss: [
                CKEDITOR.basePath + 'contents.css',
                '/static/css/contents_.css',
                '/static/css/contents_small.css',
            ]
        });
    });
    
    $('select.form-control').selectpicker({
        style: 'btn-lg'
    });
</script>

templates/page/edit_text.html
{% extends "page/edit_page.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}