core/urls.py
# coding=utf-8
__author__ = 'Artur Bacmaga'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'registration/logout.html'}, name="logout"),

                       url(r'^manage_users/$', 'core.views.manage_users', name="manage-users"),
                       url(r'^manage_users/adduser/$', 'core.views.adduser', name="add-user"),
                       url(r'^manage_users/edituser/(?P<user_id>\d+)/$', 'core.views.edit_user', name="edit-user"),
                       url(r'^manage_users/deleteuser/$', 'core.views.delete_user',
                           name="delete-user"),

                       url(r'^manage_users/edituser/(?P<user_id>\d+)/password/$', 'core.views.admin_change_password',
                           name="admin-change-password"),

                       url(r'^user_data/$', 'core.views.user_data', name="user-data"),
                       url(r'^user_password/$', 'core.views.user_password', name="user-password"),
)

core/models.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@agitive.com>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.db.models import signals
from model_utils import Choices
from core.tasks import sync_media


class SyncableFileModel(models.Model):
	SYNC_STATES = Choices(
		'waiting',
		'started',
		'synched',
		'failed'
	)
	sync_status = models.CharField(choices=SYNC_STATES, default=SYNC_STATES.waiting, editable=False, max_length=16)

	class Meta:
		abstract = True

	syncable_file_fields = []

	def get_syncable_file_fields(self):
		return self.syncable_file_fields

	def get_syncable_file_paths(self):
		paths = []
		fields = self.get_syncable_file_fields()
		for field_name in fields:
			field_file = getattr(self, field_name, None)
			if field_file:
				paths.append(field_file.name)
		return paths

	def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
		super(SyncableFileModel, self).save(force_insert, force_update, using, update_fields)
		if settings.IS_MASTER:
			sync_media.delay()


class UserProfile(models.Model):
	user = models.ForeignKey(User, unique=True)
	force_password_change = models.BooleanField(default=True)


def create_user_profile_signal(sender, instance, created, **kwargs):
	if created:
		UserProfile.objects.create(user=instance)

signals.post_save.connect(create_user_profile_signal, sender=User, dispatch_uid='core.models')

core/forms.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@agitive.com>
# Author Witold Sosnowski <albi@jabster.pl>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import TextInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.contrib.auth.models import Group
from page.models import Page


PASSWORD_REQUIREMENTS = _(
	'Password must be at least 8 characters long, it must contain a minimum of '
	'one lowercase character, one uppercase character, one digit and one non-alphanumeric character.'
)
PASSWORD_MIN_LENGTH = 8


class UserPermissionEditMixin(forms.ModelForm):
	groups = forms.ModelMultipleChoiceField(
		label=_("Permission groups"),
		widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
		help_text=_("Select what permissions the user should have."),
		queryset=Group.objects.all(),
		required=False
	)

	edited_pages = forms.ModelMultipleChoiceField(
		label=_("Edited Pages"),
		widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
		help_text=_("Select which pages this user can edit."),
		queryset=Page.objects.filter(is_permission_parent=True, active=True),
		required=False
	)

	def __init__(self, is_superuser, *args, **kwargs):
		self.is_superuser = is_superuser
		super(UserPermissionEditMixin, self).__init__(*args, **kwargs)
		if not self.is_superuser:
			self.fields['groups'].queryset = Group.objects.exclude(pk=1)
		if 'instance' in kwargs:
			self.initial['edited_pages'] = kwargs['instance'].edited_pages.values_list('pk', flat=True)

	def save(self, commit=True):
		obj = super(UserPermissionEditMixin, self).save(False)
		obj.is_superuser = self.cleaned_data['groups'].filter(pk=1).count() > 0
		if commit:
			obj.save()
			self.save_m2m()
			obj.groups = self.cleaned_data['groups']
			obj.edited_pages = self.cleaned_data['edited_pages']
		return obj


class CustomUserChangeForm(UserPermissionEditMixin, forms.ModelForm):
	username = forms.RegexField(
		label=_("Username"), max_length=30, regex=r"^[\w.@+-]+$",
		help_text=_("Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only."),
		error_messages={'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")},
		widget=TextInput(attrs={'class': 'form-control'})
	)

	def __init__(self, *args, **kwargs):
		super(CustomUserChangeForm, self).__init__(*args, **kwargs)

		self.fields['email'].required = True

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'groups', 'edited_pages']
		widgets = {
			'email': TextInput(attrs={'class': 'form-control'}),
			'first_name': TextInput(attrs={'class': 'form-control'}),
			'last_name': TextInput(attrs={'class': 'form-control'}),
		}


class CustomCreateUserForm(UserPermissionEditMixin, UserCreationForm):
	username = forms.RegexField(
		label=_("Username"), max_length=30, regex=r"^[\w.@+-]+$",
		help_text = _("Required. 30 characters or fewer. Letters, digits and "
					  "@/./+/-/_ only."),
		error_messages = {
			'invalid': _("This value may contain only letters, numbers and "
						 "@/./+/-/_ characters.")},
		widget=TextInput(attrs={'class' : 'form-control'})
		)

	password1 = forms.CharField(
		label=_("Password"),
		widget=forms.PasswordInput(attrs={'class': 'form-control'}),
		help_text=PASSWORD_REQUIREMENTS
	)
	password2 = forms.CharField(
		label=_("Password confirmation"),
		widget=forms.PasswordInput(attrs={'class': 'form-control'}),
		help_text=_("Enter the same password as above, for verification.")
	)

	def __init__(self, *args, **kwargs):
		super(CustomCreateUserForm, self).__init__(*args, **kwargs)

		self.fields['email'].required = True

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'groups', 'edited_pages']
		widgets = {
			'email': TextInput(attrs={'class': 'form-control'}),
			'first_name': TextInput(attrs={'class': 'form-control'}),
			'last_name': TextInput(attrs={'class': 'form-control'}),
			'password1': PasswordInput(attrs={'class': 'form-control'}),
			'password2': PasswordInput(attrs={'class': 'form-control'}),
		}

	def clean_password1(self):
		return clean_password1(self, 'password1')


class CustomPasswordChangeForm(SetPasswordForm):
	new_password1 = forms.CharField(
		label=_("Password"),
		widget=forms.PasswordInput(attrs={'class': 'form-control'}),
		help_text=PASSWORD_REQUIREMENTS
	)
	new_password2 = forms.CharField(
		label=_("Password confirmation"),
		widget=forms.PasswordInput(attrs={'class': 'form-control'}),
		help_text=_("Enter the same password as above, for verification.")
	)

	def clean_new_password1(self):
		return clean_password1(self, 'new_password1')


def clean_password1(form, field):
	password1 = form.cleaned_data.get(field)

	if len(password1) < PASSWORD_MIN_LENGTH:
		raise forms.ValidationError(PASSWORD_REQUIREMENTS)

	if not any(ch.islower() for ch in password1):
		raise forms.ValidationError(PASSWORD_REQUIREMENTS)

	if not any(ch.isupper() for ch in password1):
		raise forms.ValidationError(PASSWORD_REQUIREMENTS)

	if not any(ch.isdigit() for ch in password1):
		raise forms.ValidationError(PASSWORD_REQUIREMENTS)

	if password1.isalnum():
		raise forms.ValidationError(PASSWORD_REQUIREMENTS)

	return password1

core/views.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@agitive.com>
# Author Witold Sosnowski <albi@jabster.pl>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from django.contrib.auth.decorators import permission_required, login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm
from core.forms import CustomUserChangeForm, CustomCreateUserForm, CustomPasswordChangeForm


@permission_required('auth.change_user')
def manage_users(request):
	form = CustomCreateUserForm(request.user.is_superuser)
	if request.user.is_superuser:
		user_list = User.objects.all()
	else:
		user_list = User.objects.filter(is_superuser=False)
	return render_to_response('core/manage_users.html', {'user_list': user_list, 'form': form},
								context_instance=RequestContext(request))


@permission_required('auth.add_user')
def adduser(request):
	if not request.is_ajax():
		raise Http404()
	if request.method == 'POST':
		form = CustomCreateUserForm(request.user.is_superuser, request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse('')
	else:
		form = CustomCreateUserForm(request.user.is_superuser)
	return render_to_response('core/add_user.html', {'edit': False, 'form': form},
								context_instance=RequestContext(request))


@permission_required('auth.change_user')
def edit_user(request, user_id):
	if not request.is_ajax():
		raise Http404()
	user = get_object_or_404(User, pk=user_id)
	if user.is_superuser and not request.user.is_superuser:
		raise Http404()
	if request.method == 'POST':
		form = CustomUserChangeForm(request.user.is_superuser, request.POST, instance=user)
		if form.is_valid():
			form.save()
			return HttpResponse('')
	else:
		form = CustomUserChangeForm(request.user.is_superuser, instance=user)

	return render_to_response('core/edit_user.html', {'edit': True, 'form': form, 'user_object': user},
								context_instance=RequestContext(request))


@permission_required('auth.delete_user')
def delete_user(request):
	user = get_object_or_404(User, pk=request.POST['user_id'])
	user.delete()
	return HttpResponseRedirect('/accounts/manage_users/')


@permission_required('auth.change_user')
def admin_change_password(request, user_id):
	if not request.is_ajax():
		raise Http404()
	user = get_object_or_404(User, pk=user_id)
	if user.is_superuser and not request.user.is_superuser:
		raise Http404()
	if request.method == 'POST':
		form = CustomPasswordChangeForm(user, request.POST)
		if form.is_valid():
			form.save()
			if request.is_ajax():
				return HttpResponse('OK')
			else:
				return HttpResponseRedirect('/accounts/manage_users/')
	else:
		form = CustomPasswordChangeForm(None)

	return render_to_response('core/admin_change_password.html', {'form': form, 'edit_user': user},
								context_instance=RequestContext(request))

@permission_required('auth.change_user')
def user_data(request):
	if request.method == 'POST':
		form = CustomUserChangeForm(request.user.is_superuser, request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/')
	else:
		form = CustomUserChangeForm(request.user.is_superuser, instance=request.user)
	return render_to_response('core/user_data.html', {'form': form, },
								context_instance=RequestContext(request))

@login_required
def user_password(request):
	if request.method == 'POST':
		form = CustomPasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			profile = request.user.get_profile()
			profile.force_password_change = False
			profile.save()
			form.save()
			return HttpResponseRedirect('/')
	else:
		form = CustomPasswordChangeForm(None)
	return render_to_response('core/user_password.html', {'form': form, },
								context_instance=RequestContext(request))

templates/core/add_user.html
{% extends "modal.html" %}
{% load i18n %}
{% load url from future %}

{% block dialog_id %}user-add-modal{% endblock %}

{% block dialog_class %}
	{% if form.errors or edit %}
	in modal-visible
	{% endif %}
{% endblock %}

{% block dialog_action %}{% url 'add-user' %}{% endblock %}

{% block dialog_title %}
    Add user
{% endblock %}

{% block dialog_body %}
	{% csrf_token %}
    {% for field in form %}
        <div class="form-group" id="{{ field.id_for_label }}_parent">
        {{ field.label_tag }}
        
        {% if field.errors %}
        <p class="alert alert-danger">
            {% for error in field.errors %}
                {{ error|escape }}
            {% endfor %}
        {% endif %}
        
        {{ field }}
        
        {% if field.help_text %}
        <small>{{field.help_text}}</small>
        {% endif %}
        {% if field.errors %}
        </p>
        {% endif %}
        </div>
    {% endfor %}   
{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Add user" %}
</button>
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
$('#user-add-modal form').ajaxForm({
    target:'#user-add-modal',
    success: function(data)
    {
        if(data == '')
        {
            window.location.href = "{% url 'manage-users' %}";
            return false;
        }
    }
});
</script>
{% endblock %}

templates/core/admin_change_password.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}user-password-modal-{{edit_user.id}}{% endblock %}

{% block dialog_class %}
    in modal-visible
{% endblock %}

{% block dialog_action %}{% url "admin-change-password" edit_user.id %}{% endblock %}

{% block dialog_title %}Change password (user: {{ edit_user }}){% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Change password" %}
</button>
{% endblock %}


{% block dialog_script %}
<script type="text/javascript">
$('#user-password-modal-{{edit_user.id}} form').ajaxForm({
	target:'#user-password-modal-{{edit_user.id}}',
    success: function(data)
    {
        if(data == 'OK')
        {
            window.location.href = "{% url 'manage-users' %}";
            return false;
        }
    }
});
</script>
{% endblock dialog_script %}

templates/core/edit_user.html
{% extends "core/add_user.html" %}
{% load i18n %}
{% load url from future %}

{% block dialog_id %}user-edit-modal{% endblock %}

{% block dialog_class %}
	in modal-visible user-edit-modal
{% endblock %}

{% block dialog_action %}{% url 'edit-user' user_object.id %}{% endblock %}

{% block dialog_title %}
    Edit user
{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Save changes" %}
</button>
{% endblock %}


{% block dialog_script %}
<script type="text/javascript">
checkboxChange();
$('#user-edit-modal form').ajaxForm({
    target:'#user-edit-modal',
    success: function(data)
    {
        if(data == '')
        {
            window.location.href = "{% url 'manage-users' %}";
            return false;
        }
    }
});
</script>
{% endblock %}

templates/core/manage_users.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load url from future %}

{% block title %}{% trans "User management" %}{% endblock %}

{% block wysiwyg_scripts %}
    <script type="text/javascript" src="{% static "js/jquery.form.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/users.js" %}"></script>
{% endblock %}

{% block content %}
    <h1 class="text-center">{% trans "User list" %}</h1>
    <div class="table-responsive stick-bottom">
    <table class="table table-full table-striped stick-bottom" id="users-table">
    <thead>
    <tr>
        <th>{% trans "USERNAME" %}</th>
        <th>{% trans "FIRST NAME" %}</th>
        <th>{% trans "LAST NAME" %}</th>
        <th colspan="3" class="action">{% trans "ACTIONS" %}</th>
    </tr>
    </thead>
    <tbody>
    {% if user_list %}
    {% for user_obj in user_list %}
    <tr>
        <td>{{ user_obj.username }}</td>
        <td>{{ user_obj.first_name }}</td>
        <td>{{ user_obj.last_name }}</td>
        <td class="action">
            <div class="modal fade user-password-modal" id="user-password-modal-{{user_obj.id}}" tabindex="-1" role="dialog" aria-hidden="true">
            </div>
            <a href="{% url "admin-change-password" user_obj.id %}" data-toggle="modal" data-target="#user-password-modal-{{user_obj.id}}">
                {% trans "PASSWORD" %}
            </a>
        </td>
        <td class="action text-center">
            <form method="post" action="{% url 'delete-user' %}" class="remove-form">
            {% csrf_token %}
            <input type="hidden" value="{{ user_obj.id }}" name="user_id">
            <button role="submit" class="btn-action remove">
                <img src="{% static 'img/remove.png' %}">  
                {% trans "REMOVE" %}
            </button>
            </form>
        </td>
        <td class="action">

            <div class="modal fade" id="user-edit-modal-{{user_obj.id}}" tabindex="-1" role="dialog" aria-hidden="true">
            </div>

            <a href="{% url "edit-user" user_obj.id %}" data-toggle="modal" data-target="#user-edit-modal-{{user_obj.id}}">
                <img src="{% static 'img/edit.png' %}">  
                {% trans "EDIT" %}
            </a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="6" class="text-center">
            <big>{% trans "No users found" %}</big>
        </td>
    </tr>
    {% endif %}
    </tbody>
    </table>
    </div>

    {% include 'core/add_user.html' %}

    <button data-toggle="modal" data-target="#user-add-modal" class="btn btn-lg btn-block">
        <img src="{% static 'img/add.png' %}">
        {% trans "Add user" %}
    </button>

{% endblock %}

templates/core/user_data.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}Create an account{% endblock %}

{% block header_styles %}
<link href="/static/css/full-form.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <form action="" method="post" class="full-form">{% csrf_token %}
	<h1 class="text-center">Your account</h1>
	{% include 'form.html' %}
	<div class="form-group">
        {% trans "Raw passwords are not stored, so there is no way to see this user's password, but you can change the password using" %}
        <a href="{% url 'user-password' %}">{% trans 'this form' %}</a>.
    </div>

      <button role="submit" class="btn btn-primary btn-lg btn-block">SAVE CHANGES</button>
  </form>
{% endblock %}

templates/core/user_password.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}Change password{% endblock %}

{% block header_styles %}
<link href="/static/css/full-form.css" rel="stylesheet">
{% endblock %}

{% block content %}
<form action="" method="post" class="full-form">
	<h1 class="text-center">Your password</h1>

	{% csrf_token %}

	<div class="form-group">
	{% if form.old_password.errors %}<p class="alert alert-danger">{% endif %}
	<input id="id_new_password" maxlength="4096" type="password" class="form-control" placeholder="Old password" name="old_password" required autofocus>
	{% if form.old_password.errors %}
	    {% for error in form.old_password.errors %}
	        {{ error|escape }}
	    {% endfor %}
		</p>
	{% endif %}
	</div>

	<div class="form-group">
	<input id="id_new_password1" maxlength="4096" type="password" class="form-control" placeholder="New password" name="new_password1" required>
	{% if form.new_password1.errors %}
	    {% for error in form.new_password1.errors %}
	        {{ error|escape }}
	    {% endfor %}
		</p>
	{% endif %}
	</div>
	<div class="form-group">
	{% if form.new_password2.errors %}<p class="alert alert-danger">{% endif %}
	<input id="id_new_password2" maxlength="4096" type="password" class="form-control" placeholder="New password confirmation" name="new_password2" required>
	{% if form.new_password2.errors %}
	    {% for error in form.new_password2.errors %}
	        {{ error|escape }}
	    {% endfor %}
		</p>
	{% endif %}
	</div>

	<button class="btn btn-lg btn-primary btn-block" type="submit">CHANGE PASSWORD</button>
</form>

{% endblock %}