core/urls.py
# coding=utf-8
__author__ = 'Artur Bacmaga'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'registration/logout.html'}, name="logout"),

                       url(r'^manage_users/$', 'core.views.manage_users', name="manage-users"),
                       url(r'^manage_users/adduser/$', 'core.views.adduser', name="add-user"),
                       url(r'^manage_users/edituser/(?P<user_id>\d+)/$', 'core.views.edit_user', name="edit-user"),
                       url(r'^manage_users/deleteuser/$', 'core.views.delete_user',
                           name="delete-user"),

                       url(r'^manage_users/edituser/(?P<user_id>\d+)/password/$', 'core.views.admin_change_password',
                           name="admin-change-password"),

                       url(r'^user_data/$', 'core.views.user_data', name="user-data"),
                       url(r'^user_password/$', 'core.views.user_password', name="user-password"),
)

file_manager/urls.py
__author__ = 'bwj'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'file_manager.views.manage_files', name="files-home"),
                       url(r'^add_file/$', 'file_manager.views.add_file', name="add-file"),
                       url(r'^edit_file/(?P<file_id>\d+)/$', 'file_manager.views.edit_file', name="edit-file"),
                       url(r'^get_en_file/(?P<file_id>\d+)/$', 'file_manager.views.get_en_file', name="get-en-file"),
                       url(r'^get_pl_file/(?P<file_id>\d+)/$', 'file_manager.views.get_pl_file', name="get-pl-file"),
                       url(r'^delete_file/$', 'file_manager.views.delete_file', name="delete-file"),
                       )

file_manager/models.py
# -*- coding: utf-8 -*-
# Author Bartłomiej Wójcicki <bartlomiej.wojcicki@agitive.com>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from django.db import models
from django.utils import timezone
from django.conf import settings

from core.models import SyncableFileModel


class File(SyncableFileModel):
	name_en = models.CharField('Name (EN)', max_length=settings.FILE_TITLE_LENGTH)
	name_pl = models.CharField('Name (PL)', max_length=settings.FILE_TITLE_LENGTH)
	created = models.DateTimeField(default=timezone.now)
	modified = models.DateTimeField(default=timezone.now)
	version = models.IntegerField(default=0)
	size = models.IntegerField(default=0)
	file_en = models.FileField('File (EN)', upload_to='pdfs')
	file_pl = models.FileField('File (PL)', upload_to='pdfs')

	syncable_file_fields = ['file_pl', 'file_en']

	def save(self, *args, **kwargs):
		if self.pk is not None:
			orig = File.objects.get(pk=self.pk)
			changed = False
			if orig.file_en != self.file_en:
				orig.file_en.delete(save=False)
				changed = True
			if orig.file_pl != self.file_pl:
				orig.file_pl.delete(save=False)
				changed = True
			if changed:
				self.version += 1

		self.modified = timezone.now()
		super(File, self).save(*args, **kwargs)

	def to_dict(self):
		size = (self.file_en.size + self.file_pl.size) / 1e6
		size = int(size * 100 + 0.5) / 100.0
		data = dict(id=self.id, name_en=self.name_en, name_pl=self.name_pl, updated=self.modified.date().isoformat(),
		            version=self.version, size=size, url_en=self.file_en.url, url_pl=self.file_pl.url)

		return data

file_manager/forms.py
from django.forms import ModelForm
from models import *
from django.forms.widgets import TextInput

class FileForm(ModelForm):
	class Meta:
		model = File
		exclude = ('version', 'created', 'modified', 'size')
		widgets = {
			'name_en': TextInput(attrs={'class': 'form-control'}),
			'name_pl': TextInput(attrs={'class' : 'form-control'}),
		}


	def clean(self):
		cleaned_data = super(FileForm, self).clean()
		file_en = cleaned_data.get('file_en')
		file_pl = cleaned_data.get('file_pl')

		req_msg = 'This field is required.'
		ext_msg = 'Incorrect file extension. Only pdf files are supported.'

		if file_en is None:
			self._errors['file_en'] = self.error_class([req_msg])
		elif not str(file_en).lower().endswith('pdf'):
			self._errors['file_en'] = self.error_class([ext_msg])

		if file_pl is None:
			self._errors['file_pl'] = self.error_class([req_msg])
		elif not str(file_pl).lower().endswith('pdf'):
			self._errors['file_pl'] = self.error_class([ext_msg])

		return cleaned_data

file_manager/views.py
from forms import *
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext


@permission_required('file_manager.change_file')
def manage_files(request):
	files = File.objects.all()
	form = FileForm()
	return render_to_response('file_manager/manage_files.html', {'files': files, 'form': form},
	                          context_instance=RequestContext(request))


@permission_required('file_manager.add_file')
def add_file(request):
	if not request.is_ajax():
		raise Http404()
	if request.method == 'POST':
		form = FileForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponse('OK')
	else:
		form = FileForm()

	return render_to_response('file_manager/add_file.html', dict(form=form),
	                          context_instance=RequestContext(request))


@permission_required('file_manager.change_file')
def edit_file(request, file_id):
	if not request.is_ajax():
		raise Http404()
	pdf_file = get_object_or_404(File, pk=file_id)
	if request.method == 'POST':
		form = FileForm(request.POST, request.FILES, instance=pdf_file)
		if form.is_valid():
			form.save()
			return HttpResponse('OK')
	else:
		form = FileForm(instance=pdf_file)

	return render_to_response('file_manager/edit_file.html', dict(form=form, edit=True, file=pdf_file),
	                          context_instance=RequestContext(request))


def get_en_file(request, file_id):
	pdf_file = get_object_or_404(File, pk=file_id)
	return HttpResponseRedirect(pdf_file.file_en.url)

def get_pl_file(request, file_id):
	pdf_file = get_object_or_404(File, pk=file_id)
	return HttpResponseRedirect(pdf_file.file_pl.url)

@permission_required('file_manager.delete_file')
def delete_file(request):
	pdf_file = get_object_or_404(File, pk=request.POST['file_id'])
	pdf_file.delete()
	return HttpResponseRedirect('/files/')

templates/file_manager/add_file.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}file-add-modal{% endblock %}

{% block dialog_class %}
	{% if form.errors %}
	in modal-visible
	{% endif %}
{% endblock %}

{% block dialog_action %}{% url 'add-file' %}{% endblock %}

{% block dialog_title %}Add File{% endblock %}

{% block dialog_body %}
    {{ block.super }}
    <div class="upload-progress hidden">
        Uploading files:
        <div class="progress progress-striped active">
            <div class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            <span class="sr-only">0% Complete</span>
        </div>
        </div>
    </div>
    <div class="alert alert-danger hidden upload-error">Could not upload files. Please try again later.</div>
{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Add" %}
</button>
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
    $dialog = $('#file-add-modal');
    $('#file-add-modal form').ajaxForm({
        target:'#file-add-modal',
        beforeSend: function() 
        {
            if($dialog.find('#id_file_pl').val() != '' || $dialog.find('#id_file_en').val() != '')
                $dialog.find('.upload-progress').removeClass('hidden');
        },
        uploadProgress: function(event, position, total, percentComplete) 
        {
            $dialog.find('.progress-bar').css('width', percentComplete + '%')
            $dialog.find('.sr-only').html(percentComplete + '% Complete')
        },
        success: function(data)
        {
            if(data == 'OK')
            {
                window.location.href = "{% url 'files-home' %}";
                return false;
            }
        },
        error: function(data)
        {
            $dialog.find('.upload-error').removeClass('hidden');
        }
    });
</script>
{% endblock %}

templates/file_manager/edit_file.html
{% extends "file_manager/add_file.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}file-edit-modal-{{ file.id }}{% endblock %}

{% block dialog_class %}
	in modal-visible
{% endblock %}

{% block dialog_action %}{% url 'edit-file' file.id %}{% endblock %}

{% block dialog_title %}Add File{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Edit" %}
</button>
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
    $dialog = $('#file-edit-modal-{{ file.id }}');
    $dialog.find('form').ajaxForm({
        target:'#file-edit-modal-{{ file.id }}',
        beforeSend: function() 
        {
            if($dialog.find('#id_file_pl').val() != '' || $dialog.find('#id_file_en').val() != '')
                $dialog.find('.upload-progress').removeClass('hidden');
        },
        uploadProgress: function(event, position, total, percentComplete) 
        {
            $dialog.find('.progress-bar').css('width', percentComplete + '%')
            $dialog.find('.sr-only').html(percentComplete + '% Complete')
        },
        success: function(data)
        {
            if(data == 'OK')
            {
                window.location.href = "{% url 'files-home' %}";
                return false;
            }
        },
        error: function(data)
        {
            $dialog.find('.upload-error').removeClass('hidden');
        }
    });
</script>
{% endblock %}

templates/file_manager/manage_files.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% load static %}

{% block title %}{% endblock %}

{% block wysiwyg_scripts %}
    <script type="text/javascript" src="{%  static "js/jquery.form.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "js/files.js" %}"></script>
{% endblock %}

{% block content %}
    <h1 class="text-center">Files</h1>

    <div class="table-responsive stick-bottom">
    <table class="table table-striped table-full stick-bottom" id="file-table">
        <thead class="noborder">
            <tr>
                <th class="column-id">{% trans 'ID' %}</th>
                <th>{% trans 'NAME' %}</th>
                <th>{% trans 'CREATED' %}</th>
                <th colspan="3" class="action">{% trans 'ACTIONS' %}</th>
        </thead>
        <tbody>
        {% if files %}
            {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.name_en }}</td>
                <td>{{ file.created }}</td>
                <td class="action text-center">
                    <form method="post" action="{% url "delete-file" %}">
                    {% csrf_token %}
                    <input type="hidden" name="file_id" value="{{ file.id }}">
                    <button role="submit" class="btn-action file-remove" >
                        <img src="{% static 'img/remove.png' %}"> {% trans 'REMOVE' %}
                </button>
                    </form>
                </td>
                <td class="action">
                    <div class="modal fade file-edit-modal" id="file-edit-modal-{{file.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                    </div>
                    <a href="{% url "edit-file" file.id %}" data-toggle="modal" data-target="#file-edit-modal-{{file.id}}">
                        <img src="{% static 'img/edit.png' %}">  
                        {% trans "EDIT" %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6" class="text-center">{% trans "No files" %}</td>
            </tr>
        {% endif %}
        </tbody>
    <table>
    </div>

    <button data-toggle="modal" data-target="#file-add-modal" class="btn btn-lg btn-block">
        <img src="{% static 'img/add.png' %}">
        {% trans "Add file" %}
    </button>

    {% include 'file_manager/add_file.html' %}
{% endblock %}