core/urls.py
# coding=utf-8
__author__ = 'Artur Bacmaga'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'template_name': 'registration/logout.html'}, name="logout"),

                       url(r'^manage_users/$', 'core.views.manage_users', name="manage-users"),
                       url(r'^manage_users/adduser/$', 'core.views.adduser', name="add-user"),
                       url(r'^manage_users/edituser/(?P<user_id>\d+)/$', 'core.views.edit_user', name="edit-user"),
                       url(r'^manage_users/deleteuser/$', 'core.views.delete_user',
                           name="delete-user"),

                       url(r'^manage_users/edituser/(?P<user_id>\d+)/password/$', 'core.views.admin_change_password',
                           name="admin-change-password"),

                       url(r'^user_data/$', 'core.views.user_data', name="user-data"),
                       url(r'^user_password/$', 'core.views.user_password', name="user-password"),
)

video/urls.py
# coding=utf-8
__author__ = 'Artur Bacmaga'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'video.views.video_list', name='video-list'),
                       url(r'^add/$', 'video.views.video_add', name='video-add'),
                       url(r'^convert/(?P<video_id>\d+)/$', 'video.views.video_convert', name='video-convert'),
                       url(r'^convert_all/(?P<video_id>\d+)/$', 'video.views.video_convert_all', name='video-convert-all'),
                       url(r'^edit/(?P<video_id>\d+)/$', 'video.views.video_edit', name='video-edit'),
                       url(r'^preview/(?P<video_id>\d+)/$', 'video.views.video_preview', name='video-preview'),
                       url(r'^delete/$', 'video.views.video_delete', name='video-delete'),

)

video/models.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@agitive.com>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from __future__ import unicode_literals
import shutil
import urllib2
import os
import unicodedata
from django.core.files.base import File
from django.core.files.temp import NamedTemporaryFile
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models import F
from video.tasks import generate_poster_thumbnails
from video.utils import generate_media_path
from video.processors import ResizeToEdge
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeCanvas

from core.models import SyncableFileModel

YT_IMG_API = "http://img.youtube.com/vi/{0}/0.jpg"
VARIANT_FILE = "variant.m3u8"
VARIANT_SLAVE_FILE = "variant_slave.m3u8"
SCREEN320 = 320
SCREEN480 = 480
SCREEN768 = 768
SCREEN720 = 720
SCREEN1152 = 1152
SCREEN640 = 640
SCREEN960 = 960
SCREEN1536 = 1536
FILL_COLOR = (0, 0, 0, 255)

LOCAL = 'LC'
YOUTUBE = 'YT'


def get_video_upload_path(instance, filename):
	filename = unicode(filename).replace(" ", "")
	path = os.path.join('video', unicode(instance.date.strftime("%Y_%m_%d__%H_%M_%S")).replace(" ", "") + "_" + unicode(
		instance.title_en[:40]).replace(" ", ""), filename)
	return unicodedata.normalize('NFKD', path).encode('ascii', 'ignore')


def get_image_field_specs(size):
	width = size
	height = int((size / 16.0) * 9)
	return {
		'source': 'poster',
		'processors': [ResizeToEdge(width, height, upscale=True), ResizeCanvas(width, height, FILL_COLOR)],
		'format': 'JPEG',
		'options': {'quality': 80}
	}


class Video(SyncableFileModel):
	VIDEO_TYPES = (
		(YOUTUBE, 'You Tube'),
		(LOCAL, 'Local video'),
	)

	conversion = models.BooleanField(default=False)

	video_type = models.CharField(max_length=2, choices=VIDEO_TYPES, default=LOCAL)

	title_pl = models.CharField('Title (PL)', max_length=settings.FILE_TITLE_LENGTH)
	title_en = models.CharField('Title (EN)', max_length=settings.FILE_TITLE_LENGTH)

	date = models.DateTimeField(default=timezone.now)

	active = models.BooleanField(default=False)

	video_original = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_android1 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_android2 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_android3 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios1 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios2 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios3 = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios_variant = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios_variant_slave = models.FileField(upload_to=get_video_upload_path, null=True, blank=True)
	video_ios_generated_on = models.CharField(max_length=settings.FILE_TITLE_LENGTH, blank=True)

	poster = models.ImageField(upload_to=get_video_upload_path, null=True, blank=True)
	poster_time = models.PositiveIntegerField(default=1)
	poster_320 = ImageSpecField(**get_image_field_specs(SCREEN320))
	poster_480 = ImageSpecField(**get_image_field_specs(SCREEN480))
	poster_768 = ImageSpecField(**get_image_field_specs(SCREEN768))
	poster_720 = ImageSpecField(**get_image_field_specs(SCREEN720))
	poster_1152 = ImageSpecField(**get_image_field_specs(SCREEN1152))
	poster_640 = ImageSpecField(**get_image_field_specs(SCREEN640))
	poster_960 = ImageSpecField(**get_image_field_specs(SCREEN960))
	poster_1536 = ImageSpecField(**get_image_field_specs(SCREEN1536))

	url = models.URLField(max_length=settings.URL_LENGTH, null=True, blank=True)

	views = models.PositiveIntegerField(default=0)

	syncable_file_fields = [
		'video_original',
		'video_android1',
		'video_android2',
		'video_android3',
		'video_ios1',
		'video_ios2',
		'video_ios3',
		'video_ios_variant',
		'poster_320',
		'poster_480',
		'poster_768',
		'poster_720',
		'poster_1152',
		'poster_640',
		'poster_960',
		'poster_1536',
	]

	def get_syncable_file_paths(self):
		paths = super(Video, self).get_syncable_file_paths()
		paths.append(self.thumbnails_folder())
		return paths

	def __unicode__(self):
		return unicode(self.title_en)

	def delete(self, using=None):
		try:
			shutil.rmtree(self.video_original.path[:-len(os.path.basename(self.video_original.path))])
		except:
			pass

		try:
			shutil.rmtree(self.poster.path[:-len(os.path.basename(self.poster.path))])
		except:
			pass

		self.delete_thumbnails_folder()

		super(Video, self).delete()

	def generate_variant_writer(self, site, variant_filename):
		m3u8_file_path = os.path.join(self.video_original.path[:-len(os.path.basename(self.video_original.path))],
		                              variant_filename)
		m3u8_file = open(m3u8_file_path, 'w+')
		m3u8_file.write('#EXTM3U\n')
		m3u8_file.write('#EXT-X-STREAM-INF:BANDWIDTH={0}\n'.format(settings.BITRATE3 * 1024))
		m3u8_file.write(str(site) + str(self.video_ios3.url) + '\n')
		m3u8_file.write('#EXT-X-STREAM-INF:BANDWIDTH={0}\n'.format(settings.BITRATE2 * 1024))
		m3u8_file.write(str(site) + str(self.video_ios2.url) + '\n')
		m3u8_file.write('#EXT-X-STREAM-INF:BANDWIDTH={0}\n'.format(settings.BITRATE1 * 1024))
		m3u8_file.write(str(site) + str(self.video_ios1.url) + '\n')
		m3u8_file.close()
		return m3u8_file_path

	def generate_variant_m3u8(self, site, slave_site):
		m3u8_file_path = self.generate_variant_writer(site, VARIANT_FILE)
		self.video_ios_variant = generate_media_path(m3u8_file_path)

		slave_m3u8_file_path = self.generate_variant_writer(slave_site, VARIANT_SLAVE_FILE)
		self.video_ios_variant_slave = generate_media_path(slave_m3u8_file_path)

	def to_dict(self):
		data = dict(id=self.id, type=self.video_type, title_pl=self.title_pl, title_en=self.title_en,
		            date=self.date.date().isoformat(), count=self.views)

		if self.video_type == LOCAL:
			try:
				data['android_urls'] = [self.video_android1.url, self.video_android2.url, self.video_android3.url]
			except:
				data['android_urls'] = None
			try:
				data['ios_urls'] = [self.video_ios1.url, self.video_ios2.url, self.video_ios3.url]
			except:
				data['ios_urls'] = None
			try:
				if self.video_ios_generated_on == settings.MIRROR_SERVER_HTTP_ADDRESS:
					# generated on mirror - current server was slave at that moment
					data['ios_variant'] = self.video_ios_variant_slave.url
				else:
					data['ios_variant'] = self.video_ios_variant.url
			except:
				data['ios_variant'] = None
			try:
				posters = dict()
				try:
					posters['main'] = self.poster.url
				except:
					posters['main'] = None
				try:
					posters['poster_320'] = self.poster_320.url
				except:
					posters['poster_320'] = None
				try:
					posters['poster_480'] = self.poster_480.url
				except:
					posters['poster_480'] = None
				try:
					posters['poster_768'] = self.poster_768.url
				except:
					posters['poster_768'] = None
				try:
					posters['poster_720'] = self.poster_720.url
				except:
					posters['poster_720'] = None
				try:
					posters['poster_1152'] = self.poster_1152.url
				except:
					posters['poster_1152'] = None
				try:
					posters['poster_640'] = self.poster_640.url
				except:
					posters['poster_640'] = None
				try:
					posters['poster_1536'] = self.poster_1536.url
				except:
					posters['poster_1536'] = None
				try:
					posters['poster_960'] = self.poster_960.url
				except:
					posters['poster_960'] = None
				data['poster'] = posters
				#data['poster'] = {'main': self.poster.url, 'poster_320': self.poster_320.url,
				#				'poster_480': self.poster_480.url, 'poster_768': self.poster_768.url,
				#				'poster_720': self.poster_720.url, 'poster_1152': self.poster_1152.url,
				#				'poster_640': self.poster_640.url, 'poster_960': self.poster_960.url,
				#				'poster_1536': self.poster_1536.url}
			except:
				data['poster'] = None
		elif self.video_type == 'YT':
			data['yt_url'] = self.url
			try:
				data['poster'] = {'main': self.poster.url, 'poster_320': self.poster_320.url,
									'poster_480': self.poster_480.url, 'poster_768': self.poster_768.url,
									'poster_720': self.poster_720.url, 'poster_1152': self.poster_1152.url,
									'poster_640': self.poster_640.url, 'poster_960': self.poster_960.url,
									'poster_1536': self.poster_1536.url}
			except:
				data['poster'] = None

		return data

	def increment_view_count(self):
		self.views = F('views') + 1
		self.save()

	def get_yt_id(self):
		return unicode(self.url).split('?v=')[-1]

	def get_yt_poster(self):
		if self.video_type == LOCAL:
			return
		filename = u"yt_thumb.jpg"
		url = YT_IMG_API.format(self.get_yt_id())
		temp_file = NamedTemporaryFile(delete=True)
		temp_file.write(urllib2.urlopen(url).read())
		temp_file.flush()
		if self.poster:
			os.remove(self.poster.path)
		self.poster.save(filename, File(temp_file))
		generate_poster_thumbnails(self)

	def video_type_name(self):
		if self.video_type == LOCAL:
			return 'Local'
		else:
			return 'Youtube'

	def is_local(self):
		return self.video_type == LOCAL

	def thumbnails_folder(self):
		return self.poster_320.path[:-len(os.path.basename(self.poster_320.path))]

	def delete_thumbnails_folder(self):
		try:
			shutil.rmtree(self.thumbnails_folder())
		except:
			pass

video/views.py
# -*- coding: utf-8 -*-
# Author Artur Baćmaga <artur.bacmaga@agitive.com>
# Author Szymon Nowicki <szymon.nowicki@agitive.com>
# (C) Agitive sp. z o. o. 2014

from django.http.response import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from django.contrib.auth.decorators import permission_required, login_required
from django.conf import settings
from video.forms import VideoForm, VideoPosterForm
from video.models import Video
from video.utils import generate_media_path, get_video_thumb, generate_image_path, get_video_duration
from video.tasks import convert_all_video, generate_poster_thumbnails

VIDEO_THUMB_NAME = "video_thumb.jpg"


@permission_required('video.change_video')
def video_list(request):
	form = VideoForm()
	video_list = Video.objects.all()
	convert_count = Video.objects.filter(conversion=True).count()
	site = 'http://' + str(request.META.get('HTTP_HOST', ""))
	return render_to_response('video/video_list.html', {'convert_count': convert_count, 'video_list': video_list, 'site': site, 'form': form},
	                          context_instance=RequestContext(request))

@login_required
def video_preview(request, video_id):
	if not request.is_ajax():
		raise Http404()
	video = get_object_or_404(Video, pk=video_id)
	return render_to_response('video/video_preview.html', {'video': video})

@permission_required('video.add_video')
def video_add(request):
	if request.method == 'POST':
		form = VideoForm(request.POST, request.FILES)
		if form.is_valid():
			video = form.save()
			if video.is_local():
				video_path = video.video_original.path
				img_file_path = generate_image_path(video_path, VIDEO_THUMB_NAME)
				get_video_thumb(video_path, img_file_path)
				video.poster = generate_media_path(img_file_path)
				video.save()
				return HttpResponseRedirect('/video/convert/{0}'.format(video.id))
			video.active = True
			video.save()
			video.get_yt_poster()
			return HttpResponse('')
	else:
		form = VideoForm()
	return render_to_response('video/video_add.html', {'form': form },
	                          context_instance=RequestContext(request))


@permission_required('video.change_video')
def video_edit(request, video_id):
	if not request.is_ajax():
		raise Http404()
	video = get_object_or_404(Video, pk=video_id)
	if request.method == 'POST':
		form = VideoForm(request.POST, request.FILES, instance=video)
		if form.is_valid():
			convert = 'video_original' in form.changed_data
			video = form.save()
			if video.is_local():
				if convert:
					video_path = video.video_original.path
					img_file_path = generate_image_path(video_path, VIDEO_THUMB_NAME)
					get_video_thumb(video_path, img_file_path)
					video.poster = generate_media_path(img_file_path)
					video.active = False
					video.save()
					return HttpResponseRedirect('/video/convert/{0}'.format(video.id))
				else:
					return HttpResponse('')
			video.active = True
			video.save()
			video.get_yt_poster()
			return HttpResponse('')
	else:
		form = VideoForm(instance=video)
	return render_to_response('video/video_edit.html', {'form': form, 'video': video },
	                          context_instance=RequestContext(request))

@permission_required('video.delete_video')
def video_delete(request):
	video_id = request.POST.get('video_id', None)
	if video_id is None:
		raise Http404()
	video = get_object_or_404(Video, pk=video_id)
	video.delete()
	return HttpResponseRedirect('/video/')


@permission_required('video.change_video')
def video_convert(request, video_id):
	if not request.is_ajax():
		raise Http404()
	video = get_object_or_404(Video, pk=video_id)
	if not video.is_local():
		raise Http404()
	seconds = get_video_duration(video.video_original.path)
	form = VideoPosterForm(seconds=seconds)

	return render_to_response('video/video_convert.html', {'video': video, 'form': form},
	                          context_instance=RequestContext(request))


@permission_required('video.change_video')
def video_convert_all(request, video_id):
	video = get_object_or_404(Video, pk=video_id)
	if not video.is_local():
		raise Http404()
	generate_poster_thumbnails.delay(video)
	if not video.active:
		video.conversion = True
		video.video_ios_generated_on = 'http://' + str(request.META.get('HTTP_HOST', ""))
		video.save()
		convert_all_video.delay(video, video.video_ios_generated_on, settings.MIRROR_SERVER_HTTP_ADDRESS)
	return render_to_response('video/video_convert_message.html',
	                          context_instance=RequestContext(request))

templates/video/video_add.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}video-add-modal{% endblock %}

{% block dialog_class %}
	{% if form.errors %}
	in modal-visible
	{% endif %}
{% endblock %}

{% block dialog_action %}{% url 'video-add' %}{% endblock %}

{% block dialog_title %}Add Video{% endblock %}

{% block dialog_body %}
    {{ block.super }}
    <div class="upload-progress hidden">
        Uploading video:
        <div class="progress progress-striped active">
            <div class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            <span class="sr-only">0% Complete</span>
        </div>
        </div>
    </div>
    <div class="alert alert-danger hidden upload-error">Could not upload files. Please try again later.</div>
{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Add" %}
</button>
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
    if ($('#id_video_type').val() == 'YT')
    {
        $('#id_video_original_parent').hide();
        $('#id_url_parent').show();
    }
    else 
    {
        $('#id_video_original_parent').show();
        $('#id_url_parent').hide();
    }
    
    $dialog = $('#video-add-modal');
    $dialog.find('form').ajaxForm({
        target:'#video-add-modal',
        beforeSend: function() 
        {
            if($dialog.find('#id_video_original').val() != '')
                $dialog.find('.upload-progress').removeClass('hidden');
        },
        uploadProgress: function(event, position, total, percentComplete) 
        {
            $dialog.find('.progress-bar').css('width', percentComplete + '%')
            $dialog.find('.sr-only').html(percentComplete + '% Complete')
        },
        success: function(data)
        {
            if(data == '')
            {
                window.location.href = "{% url 'video-list' %}";
                return false;
            }
        },
        error: function(data)
        {
            $dialog.find('.upload-error').removeClass('hidden');
        }
    });
</script>
{% endblock %}

templates/video/video_convert.html
{% extends "modal.html" %}
{% load url from future %}
{% load i18n %}

{% block dialog_id %}video-convert-modal{% endblock %}

{% block dialog_class %}
    in modal-visible
{% endblock %}

{% block dialog_action %}{% endblock %}

{% block dialog_title %}{% trans "Choose thumbnail" %}{% endblock %}

{% block dialog_body %}
    {% if video.poster_1536 %}
    <p>
        <img id="video-thumb" src="{{ video.poster_1536.url }}"/>
    <p>
    {{ form.second }} 
    {% trans "sec" %} 
    <button id="get-thumb" class="btn btn-lg">
        {% trans "Generate new" %}
    </button> 

    {% else %}
        <p class="alert alert-danger">{% trans "Generate thumbnail error" %}.</p>
    {% endif %}
{% endblock %}

{% block dialog_buttons %}
    <a href="{% url 'video-convert-all' video.id %}" class="btn btn-primary">

    {% if not video.active %}
        {% trans "Start conversion" %}
    {% else %}
        {% trans "Save" %}
    {% endif %}
    </a>

    {% if not video.active %}
        <p class="dialog-button-info">{% trans "Click this button to start conversion for iOS and Android devices. This operation can takes few minutes" %}.</p>
    {% endif %}
{% endblock %}

{% block dialog_script %}
<script type="text/javascript">
    video_id = {{video.id}}
</script>
<script src="/static/js/get_thumb.js" type="text/javascript"></script>
{% endblock %}

templates/video/video_convert_message.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
    <h2>{% autoescape off %}{{ message }}{% endautoescape %}</h2><br/>
    <a href="{% url 'video-list' %}">{% trans "Go back to video list" %}</a>
{% endblock %}

templates/video/video_edit.html
{% extends "video/video_add.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}video-edit-modal{% endblock %}

{% block dialog_class %}
    in modal-visible
{% endblock %}

{% block dialog_action %}{% url 'video-edit' video.id %}{% endblock %}

{% block dialog_title %}Edit Video{% endblock %}

{% block dialog_buttons %}
<button type="submit" class="btn btn-primary">
	{% trans "Edit" %}
</button>
{% if video.is_local %}
	<button class="btn pull-left thumb-edit">
	    {% trans "Edit thumbnail" %}
	</button>
{% endif %}
{% endblock %}


{% block dialog_script %}
<script type="text/javascript">
    if ($('#id_video_type').val() == 'YT')
    {
        $('#id_video_original_parent').hide();
        $('#id_url_parent').show();
    }
    else 
    {
        $('#id_video_original_parent').show();
        $('#id_url_parent').hide();
    }
    
    $dialog = $('#video-edit-modal-{{video.id}}');
	$dialog.find('.thumb-edit').click(function(){
		$.get('{% url 'video-convert' video.id %}', function(data){
			$dialog.html(data);
		});
		return false;
	});    
    $dialog.find('form').ajaxForm({
        target:'#video-edit-modal-{{video.id}}',
        beforeSend: function() 
        {
            if($dialog.find('#id_video_original').val() != '')
                $dialog.find('.upload-progress').removeClass('hidden');
        },
        uploadProgress: function(event, position, total, percentComplete) 
        {
            $dialog.find('.progress-bar').css('width', percentComplete + '%')
            $dialog.find('.sr-only').html(percentComplete + '% Complete')
        },
        success: function(data)
        {
            if(data == '')
            {
                window.location.href = "{% url 'video-list' %}";
                return false;
            }
        },
        error: function(data)
        {
            $dialog.find('.upload-error').removeClass('hidden');
        }
    });
</script>
{% endblock %}

templates/video/video_list.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load static %}

{% block wysiwyg_scripts %}
    <script type="text/javascript" src="{%  static "js/jquery.form.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "js/videos.js" %}"></script>
{% endblock %}

{% block header_styles %}
<link rel="stylesheet" href="/static/css/video.css">
{% endblock %}

{% block content %}
    <h1 class="text-center">Videos</h1>

    <div class="table-responsive stick-bottom">
    <table class="table table-striped table-full stick-bottom" id="video-table">
        <thead class="noborder">
            <tr>
                <th class="column-id">{% trans 'ID' %}</th>
                <th>{% trans 'TITLE' %}</th>
                <th>{% trans 'TYPE' %}</th>
                <th>{% trans 'CREATED' %}</th>
                <th colspan="3">{% trans 'INFO' %}</th>
        </thead>
        <tbody>

        {% if video_list %}
        {% for video in video_list %}

        {% if video.active or video.conversion or video.type == 'YT' %}
        <tr>
        {% else %}
        <tr class="error">
        {% endif %}

            <td class="column-id">{{ video.id }}</td>
            <td>{{ video.title_en }}/{{ video.title_pl }}</td>
            <td>{{ video.video_type_name }}</td>
            <td>{{ video.date }}</td>
            {% if video.conversion %}
            <td colspan="3">
                Conversion in progress. Video will be available soon.
            </td>
            {% else %}
            <td class="action">
                <div class="modal fade" id="video-preview-modal-{{video.id}}" tabindex="-1" role="dialog" aria-hidden="true"></div>

                {% if video.active or video.type == 'YT' %}
                <a href="{% url 'video-preview' video.id %}" data-toggle="modal" data-target="#video-preview-modal-{{video.id}}">
                    {% trans "PREVIEW" %}
                </a>
                {% else %}
                    <div class="text-center">{% trans "ERROR" %}</div>
                {% endif %}
            </td>
            <td class="action text-center">
                <form method="post" action="{% url "video-delete" %}">
                {% csrf_token %}
                <input type="hidden" name="video_id" value="{{ video.id }}">
                <button role="submit" class="btn-action video-remove" >
                    <img src="{% static 'img/remove.png' %}"> {% trans 'REMOVE' %}
            </button>
                </form>
            </td>
            <td class="action">
                <div class="modal fade video-edit-modal" id="video-edit-modal-{{video.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                </div>
                <a href="{% url "video-edit" video.id %}" data-toggle="modal" data-target="#video-edit-modal-{{video.id}}">
                    <img src="{% static 'img/edit.png' %}">  
                    {% trans "EDIT" %}
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    {% else %}
        <tr>
            <td colspan="6" class="text-center">{% trans "No videos" %}</td>
        </tr>
    {% endif %}    
    </tbody>
    </table>
    </div>
    
    {% if convert_count == 0 %}
        <button data-toggle="modal" data-target="#video-add-modal" class="btn btn-lg btn-block">
            <img src="{% static 'img/add.png' %}">
            {% trans "Add video" %}
        </button>
        {% include 'video/video_add.html' %}
    {% else %}
    <div data-original-title="Cannot add new videos - conversion in progress." class="hover-tooltip">
        <button class="btn btn-lg btn-block disabled">
            <img src="{% static 'img/add.png' %}">
            {% trans "Add video" %}
        </button>
    </div>
    {% endif %}
{% endblock %}

templates/video/video_preview.html
{% extends "modal.html" %}

{% load url from future %}
{% load i18n %}

{% block dialog_id %}video-preview-modal{% endblock %}

{% block dialog_class %}
	in modal-visible
{% endblock %}

{% block dialog_action %}{% endblock %}

{% block dialog_title %}Video preview{% endblock %}

{% block dialog_body %}
    {% if video.video_type == 'YT' %}
        <iframe width="560" height="315" src="//www.youtube.com/embed/{{ video.get_yt_id }}?wmode=transparent" frameborder="0" allowfullscreen></iframe>
    {% else %}
        <video controls poster="{{ site }}{{ video.poster.url }}">
            <source src="{{ site }}{{video.video_android1.url}}" type="video/mp4">
        </video>
    {% endif %}
{% endblock %}

{% block dialog_buttons %}
    {% if video.video_type == 'LC' %}
        <a href="{{ site }}{{ video.video_android1.url }}" class="btn btn-default">Direct link</a>
    {% endif %}
{% endblock %}


{% block dialog_script %}
<script type="text/javascript">
$('#user-add-modal form').ajaxForm({
    target:'#user-add-modal',
    success: function(data)
    {
        if(data == '')
        {
            window.location.href = "{% url 'manage-users' %}";
            return false;
        }
    }
});

$('.modal').on('hidden.bs.modal', function(){
    if($(this).find('video').length > 0)
        $(this).find('video')[0].pause();
});
</script>
{% endblock %}